import React, {useState, useEffect} from "react";
import {GoogleSpreadsheet} from 'google-spreadsheet';
import {
  BrowserRouter as Router,
  Routes,
  Route
} from "react-router-dom";
import About from './pages/About';
import Dashboard from './pages/Dashboard';
import LandingPage from './pages/LandingPage';
import netlifyIdentity from 'netlify-identity-widget';

const {REACT_APP_SHEET_ID} = process.env;
const {REACT_APP_GOOGLE_CLIENT_EMAIL} = process.env;
const {REACT_APP_GOOGLE_PRIVATE_KEY} = process.env;

export default function App() {
  const [coinData, setCoinData] = useState([]);
  const [user, setUser] = useState('')
  const [doc, setDoc] = useState({});

  netlifyIdentity.on('login', () => {
    setUser(netlifyIdentity.currentUser().user_metadata.full_name)
  })

  netlifyIdentity.on('logout', () => {
    setUser('')
  })

  useEffect(() => {
    if(netlifyIdentity.currentUser()) {
      setUser(netlifyIdentity.currentUser().user_metadata.full_name)
    }
    const googleDoc = new GoogleSpreadsheet(REACT_APP_SHEET_ID);

    (async function() {
        await googleDoc.useServiceAccountAuth({
            // env var values are copied from service account credentials generated by google
            // see "Authentication" section in docs for more info
            client_email: REACT_APP_GOOGLE_CLIENT_EMAIL,
            private_key: REACT_APP_GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
          });
          await googleDoc.loadInfo(); // loads document properties and worksheets
          console.log(googleDoc);
          setDoc(googleDoc)
    }())
  }, [])
  
  return (
    <Router>
      <div>
        {/* A <Routes> looks through its children <Route>s and
            renders the first one that matches the current URL. */}
        <Routes>
          <Route path="/about" element={<About />} />
          <Route path="/dashboard" element={<Dashboard coinData={coinData} setCoinData={setCoinData} user={user} doc={doc} />} />
          <Route path="/" element={<LandingPage user={user} />} />
        </Routes>
      </div>
    </Router>
  );
}
